# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

os:
  - linux
  - osx

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - os: osx
      python: 3.4
      language: generic
    - os: osx
      python: 3.5
      language: generic
    - os: osx
      python: 3.6
      language: generic
    allow_failures:
      - os: osx
  
before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      sudo apt-get -y install python3 python3-setuptools
      
      ## Install sip and pyqt5
      #export DISPLAY=:99.0
      #sh -e /etc/init.d/xvfb start
      
      # Cached Downloads
      #sudo mkdir -p /downloads
      #sudo chmod a+rw /downloads
      #curl -L -o /downloads/sip.tar.gz https://nchc.dl.sourceforge.net/project/pyqt/sip/sip-4.18/sip-4.18.tar.gz
      #curl -L -o /downloads/PyQt5_gpl-5.6.tar.gz https://superb-dca2.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz
      
      # Builds
      #sudo mkdir -p /builds
      #sudo chmod a+rw /builds
      
      # Qt5
      #sudo add-apt-repository -y ppa:beineri/opt-qt562
      #sudo apt-get update
      #sudo apt-get install -y qt56base
      
      # Builds
      #pushd /builds
      
      # SIP
      #tar xzf /downloads/sip.tar.gz --keep-newer-files
      #pushd sip-4.18
      #python configure.py
      #make
      #sudo make install
      #popd
      
      # PyQt5
      #source /opt/qt56/bin/qt56-env.sh  # switch to Qt5
      #tar xzf /downloads/PyQt5_gpl-5.6.tar.gz --keep-newer-files
      #pushd PyQt5_gpl-5.6
      #python configure.py -c --confirm-license --verbose --no-designer-plugin -e QtWidgets -e QtCore -e QtGui -e QtPrintSupport
      #make
      #sudo make install
      #popd
      
      # Out from builds
      #popd
      
    else
      rvm get stable
      brew update
      brew install python3
      brew install pyqt5 --with-python3
    fi

install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
    
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    pip install Cython --install-option="--no-cython-compile"
    pip install --upgrade numpy
    pip install --upgrade scipy
    pip install --upgrade matplotlib
    pip install --upgrade h5py

    # Install gcMapExplorer
    pip install -ve .
    
    else
    
    pip3 install --upgrade pip
    pip3 install --upgrade wheel
    pip3 install --upgrade setuptools
    pip3 install Cython --install-option="--no-cython-compile"
    pip3 install --upgrade numpy
    pip3 install --upgrade scipy
    pip3 install --upgrade matplotlib
    pip3 install --upgrade h5py

    # Install gcMapExplorer
    pip3 install -ve .
    fi


script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then python -c 'import gcMapExplorer' ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then python -c 'import gcMapExplorer.lib as gmlib' ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 -c 'import gcMapExplorer' ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 -c 'import gcMapExplorer.lib as gmlib' ; fi


deploy:
  # test pypi
  - provider: pypi
    distributions: "sdist bdist_wheel"
    server: https://testpypi.python.org/pypi
    user: "rjdkmr"
    password:
      secure: G/ZcM1wmx8lhZ86SgjK6GYadl86Jbpsjh2Ri35ttUPDUABf/HKe5JjRqjthVvUc3k6tzN8i2hXx8SKICqmlgq0j7u8y2Emty4OF4q2dVWRr7/XuFL/YsUYGU4FGUsyeMvPNmr9ShUXnwMSoNeFNf414VtppHjP+Tc0jyNd800tgQSFALNG5B3SH1/cIYdiUtsitNOVA+gqPoYoHDItGiS8GrQiFGaYGtVejxAOqvzURjJE/Tr6YIxVn7ZIgF2nbGEcafo+yVt0leTYW9+pp5wUoVkurwKRToMBdalnkb2XvstwsYpOqlOtepVruWKGHOH9wYSP2oddD3IvtHKiOW33jNrRQRX5kye0UIu6MPzOwuigQ8vxZbbET84vMwOrwX9xLHrw09K0lTg0rpPZX7tdh+3bQ/WUKmLjMwleW7nl3oOSfub3CWBKvZ92gchnC12lDANN6vorfPWi9TuhUENqqCrlF/pRsuKTE7NOtWHiEBEds7t8QhJoOouHehPEbAiBQ4uMd5yxkGHGio6hfJ9MV69Z51SLRVUtPp4pwzlstgSS342gQ8DstsBUxmXiBqCwbUkquHs28tB9XLSEXhklT37xFZjvouOFI3I89NrS/jEV4jKMVlQL7EDhTvYSKf1VCia3oKzM89iDQtrzx9wzE9ziGV0z5jAxqbuMpig0g=
    on:
      branch: master
      tags: false
      
  # production pypi
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: "rjdkmr"
    password:
      secure: G/ZcM1wmx8lhZ86SgjK6GYadl86Jbpsjh2Ri35ttUPDUABf/HKe5JjRqjthVvUc3k6tzN8i2hXx8SKICqmlgq0j7u8y2Emty4OF4q2dVWRr7/XuFL/YsUYGU4FGUsyeMvPNmr9ShUXnwMSoNeFNf414VtppHjP+Tc0jyNd800tgQSFALNG5B3SH1/cIYdiUtsitNOVA+gqPoYoHDItGiS8GrQiFGaYGtVejxAOqvzURjJE/Tr6YIxVn7ZIgF2nbGEcafo+yVt0leTYW9+pp5wUoVkurwKRToMBdalnkb2XvstwsYpOqlOtepVruWKGHOH9wYSP2oddD3IvtHKiOW33jNrRQRX5kye0UIu6MPzOwuigQ8vxZbbET84vMwOrwX9xLHrw09K0lTg0rpPZX7tdh+3bQ/WUKmLjMwleW7nl3oOSfub3CWBKvZ92gchnC12lDANN6vorfPWi9TuhUENqqCrlF/pRsuKTE7NOtWHiEBEds7t8QhJoOouHehPEbAiBQ4uMd5yxkGHGio6hfJ9MV69Z51SLRVUtPp4pwzlstgSS342gQ8DstsBUxmXiBqCwbUkquHs28tB9XLSEXhklT37xFZjvouOFI3I89NrS/jEV4jKMVlQL7EDhTvYSKf1VCia3oKzM89iDQtrzx9wzE9ziGV0z5jAxqbuMpig0g=
    on:
      branch: master
      tags: true
