# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

os:
  - linux
  - osx

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.4
      env: TOXENV=py34
    - os: linux
      sudo: required
      python: 3.5
      env: TOXENV=py35
    - os: linux
      sudo: required
      python: 3.6
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py34
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
  
before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      sudo apt-get -y install python3 python3-setuptools
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      
      # Cached Downloads
      sudo mkdir -p /downloads
      sudo chmod a+rw /downloads
      curl -L -o /downloads/sip.tar.gz https://nchc.dl.sourceforge.net/project/pyqt/sip/sip-4.18/sip-4.18.tar.gz
      curl -L -o /downloads/PyQt5_gpl-5.6.tar.gz https://superb-dca2.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz
      
      # Builds
      sudo mkdir -p /builds
      sudo chmod a+rw /builds
      
      # Qt5
      sudo add-apt-repository -y ppa:beineri/opt-qt562
      sudo apt-get update
      sudo apt-get install -y qt56base
      
      #Builds
      pushd /builds
      # SIP
      tar xzf /downloads/sip.tar.gz --keep-newer-files
      pushd sip-4.18
      python configure.py
      make
      sudo make install
      popd
      
      # PyQt5
      source /opt/qt56/bin/qt56-env.sh  # switch to Qt5
      tar xzf /downloads/PyQt5_gpl-5.6.tar.gz --keep-newer-files
      pushd PyQt5_gpl-5.6
      python configure.py -c --confirm-license --verbose --no-designer-plugin -e QtWidgets -e QtCore -e QtGui -e QtPrintSupport
      make
      sudo make install
      popd
      
      # Out from builds
      popd
      
    else
      rvm get stable
      brew update
      brew install python3
      brew install pyqt5 --with-python3
    fi

install:
  - |
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    pip install Cython --install-option="--no-cython-compile"
    pip install --upgrade numpy
    pip install --upgrade scipy
    pip install --upgrade matplotlib
    pip install --upgrade h5py

    # Install gcMapExplorer
    pip install -ve .

script:
  - python -c 'import PyQt5'
  - python -c 'import gcMapExplorer'
  - python -c 'import gcMapExplorer.lib as gmlib'
