# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python


# Run jobs on container-based infrastructure, can be overridden per job
sudo: required

cache:
  directories:
    - $HOME/.cache/pip'

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      sudo apt-get -y install python3 python3-setuptools
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      
      # Cached Downloads
      sudo mkdir -p /downloads
      sudo chmod a+rw /downloads
      curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz
      curl -L -o /downloads/PyQt-gpl-5.4.tar.gz https://superb-dca2.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.4/PyQt-gpl-5.4.tar.gz
      
      # Builds
      sudo mkdir -p /builds
      sudo chmod a+rw /builds
      
      # Qt5
      sudo add-apt-repository -y ppa:beineri/opt-qt542
      sudo apt-get update
      sudo apt-get install -y qt54base
      
      #Builds
      pushd /builds
      # SIP
      tar xzf /downloads/sip.tar.gz --keep-newer-files
      pushd sip-4.16.5
      python configure.py
      make
      sudo make install
      popd
      
      # PyQt5
      source /opt/qt54/bin/qt54-env.sh  # switch to Qt5
      tar xzf /downloads/PyQt-gpl-5.4.tar.gz --keep-newer-files
      pushd PyQt-gpl-5.4
      python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtWidgets
      make
      sudo make install
      popd
      
      # Out from builds
      popd
      
    else
      brew update
      brew install python3
      brew install pyqt5 --with-python3
    fi

install:
  - |
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    pip install Cython --install-option="--no-cython-compile"
    pip install --upgrade numpy
    pip install --upgrade scipy
    pip install --upgrade matplotlib
    pip install --upgrade h5py

    # Install gcMapExplorer
    pip install -ve .
