# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python


# Run jobs on container-based infrastructure, can be overridden per job
sudo: required

cache:
  directories:
    - $HOME/.cache/pip'

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      sudo apt-get -y install python3 python3-setuptools python3-pyqt5
    else
      brew update
      brew install python3
      brew install pyqt5 --with-python3
    fi

install:
  - |
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    pip install Cython --install-option="--no-cython-compile"

    # Install gcMapExplorer
    pip install -ve .
